// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/scaler/client/client.go

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	gojenkins "github.com/bndr/gojenkins"
	client "github.com/bringg/jenkins-autoscaler/pkg/scaler/client"
	gomock "github.com/golang/mock/gomock"
)

// MockJenkinsAccessor is a mock of JenkinsAccessor interface.
type MockJenkinsAccessor struct {
	ctrl     *gomock.Controller
	recorder *MockJenkinsAccessorMockRecorder
}

// MockJenkinsAccessorMockRecorder is the mock recorder for MockJenkinsAccessor.
type MockJenkinsAccessorMockRecorder struct {
	mock *MockJenkinsAccessor
}

// NewMockJenkinsAccessor creates a new mock instance.
func NewMockJenkinsAccessor(ctrl *gomock.Controller) *MockJenkinsAccessor {
	mock := &MockJenkinsAccessor{ctrl: ctrl}
	mock.recorder = &MockJenkinsAccessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJenkinsAccessor) EXPECT() *MockJenkinsAccessorMockRecorder {
	return m.recorder
}

// DeleteNode mocks base method.
func (m *MockJenkinsAccessor) DeleteNode(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNode", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNode indicates an expected call of DeleteNode.
func (mr *MockJenkinsAccessorMockRecorder) DeleteNode(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNode", reflect.TypeOf((*MockJenkinsAccessor)(nil).DeleteNode), ctx, name)
}

// GetAllNodes mocks base method.
func (m *MockJenkinsAccessor) GetAllNodes(ctx context.Context) (client.Nodes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNodes", ctx)
	ret0, _ := ret[0].(client.Nodes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNodes indicates an expected call of GetAllNodes.
func (mr *MockJenkinsAccessorMockRecorder) GetAllNodes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNodes", reflect.TypeOf((*MockJenkinsAccessor)(nil).GetAllNodes), ctx)
}

// GetCurrentUsage mocks base method.
func (m *MockJenkinsAccessor) GetCurrentUsage(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentUsage", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUsage indicates an expected call of GetCurrentUsage.
func (mr *MockJenkinsAccessorMockRecorder) GetCurrentUsage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUsage", reflect.TypeOf((*MockJenkinsAccessor)(nil).GetCurrentUsage), ctx)
}

// GetNode mocks base method.
func (m *MockJenkinsAccessor) GetNode(ctx context.Context, name string) (*gojenkins.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNode", ctx, name)
	ret0, _ := ret[0].(*gojenkins.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNode indicates an expected call of GetNode.
func (mr *MockJenkinsAccessorMockRecorder) GetNode(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNode", reflect.TypeOf((*MockJenkinsAccessor)(nil).GetNode), ctx, name)
}
