run:
  timeout: 3m

linters:
  disable-all: true
  enable:
  - gofmt
  - goimports
  - revive
  - staticcheck
  - gocyclo
  - ineffassign
  - misspell
  - gocritic
  - govet
  - unconvert
  - promlinter
  - prealloc
  - unused

linters-settings:
  prealloc:
    simple: true
    for-loops: true
    range-loops: true

issues:
  exclude-rules:
  # don't complain about dot imports in test files
  - path: '(.+)_test\.go'
    text: should not use dot imports
    linters:
    - revive
