scaler:
  log_level: debug
  dry_run: true
  run_interval: 3s
  gc_run_interval: 3s
  scale_up_grace_period: 5m
  scale_down_grace_period: 10m
  scale_down_grace_period_during_working_hours: 1h
  controller_node_name: Built-In Node
  scale_up_threshold: 70
  scale_down_threshold: 30
  max_nodes: 10
  min_nodes_during_working_hours: 2
  jenkins_url: https://my.jenkins.co
  jenkins_user: ""
  jenkins_token: ""

backend:
  gce:
    project: gcp-project
    region: us-east1
    instance_group_manager: jenkins-nodes
  aws:
    autoscaling_group_name: jenkins-nodes
