name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25.0

    - name: Install Tools
      run: make tools

    - name: Test
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.out
        functionalities: fix
